services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    environment:
      - APP_URL=http://localhost:8090
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      
  dockpeek-agent:
    image: henrygd/beszel-agent
    container_name: dockpeek-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./beszel_agent_data:/var/lib/beszel-agent
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 3420
      KEY: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPWnxt8I9wbt9lPOT1cE5NglOH5CAwn30Rfk72m8Xemx'
      TOKEN: 6b68-d09d32a934-14af0-da95e619f
      HUB_URL: http://localhost:8090    
