version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    restart: unless-stopped
    environment:
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
    networks:
      - cloudflare-network

networks:
  cloudflare-network:
    external: true

